name:                beguile
version:             0.1.0.0
github:              "githubuser/beguile"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/beguile#readme>

default-extensions:
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- wai
- wai-conduit
- conduit
- conduit-extra
- warp
- text
- binary
- http-types
- bytestring

library:
  source-dirs: src

executables:
  beguile:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - beguile

tests:
  beguile-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - beguile
