name:                beguile
version:             0.1.0.0
github:              "turnage/beguile"
license:             BSD3
author:              "Payton Turnage"
copyright:           "2020 Payton Turnage"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            "HTTP Proxy"
category:            Web

description:         Please see the README on GitHub at <https://github.com/turnage/beguile#readme>

default-extensions:
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- options
- async
- wai
- wai-conduit
- conduit
- conduit-extra
- warp
- binary
- http-types
- bytestring
- bytestring-conversion

library:
  source-dirs: src

executables:
  beguile:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - beguile

tests:
  beguile-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - beguile
